services:
  opencv-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: opencv-gstreamer:latest
    stdin_open: true
    tty: true
    hostname: opencv-container
    working_dir: /root